### ISSUE TITLE
`this.helpers` not recognized in helper Typescript file in CodeceptJS v3; worked okay in v2

### ISSUE THREAD

**Issue by xray100** [codecept-js/CodeceptJS#2392]
#### What are you trying to achieve?
Create a Puppeteer helper using Typescript

#### What do you get instead?

**This worked okay in codeceptjs@2.6.2 but in codeceptjs@3.0.0-beta.2**, receive the following error message in Visual Studio Code and in console (when run CodeceptJS command for generating steps.d.ts file):

> Console output.

```bash
thisuser@mymachine codecept-v3 % npm run test:def

> codecept-v3@1.0.0 test:def /Users/thisuser/develop/codecept-v3
> TS_NODE_PROJECT='./src/tests/tsconfig.json' codeceptjs def --config ./codecept.conf.js --output ./src/tests/


/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/lib/container.js:179
      throw new Error(`Could not load helper ${helperName} from module '${moduleName}':\n${err.message}`);
            ^
Error: Could not load helper Extend_puppeteer_2 from module '/Users/thisuser/develop/codecept-v3/extend_puppeteer_2_helper.ts':
⨯ Unable to compile TypeScript:
extend_puppeteer_2_helper.ts:6:23 - error TS2339: Property 'helpers' does not exist on type 'Extend_puppeteer_2'.

6     const page = this.helpers['Puppeteer'].page;
                        ~~~~~~~

    at createHelpers (/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/lib/container.js:179:13)
    at Function.create (/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/lib/container.js:43:25)
    at Codecept.init (/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/lib/codecept.js:57:15)
    at Command.module.exports (/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/lib/command/definitions.js:41:12)
    at Command.listener (/Users/thisuser/develop/codecept-v3/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (/Users/thisuser/develop/codecept-v3/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/thisuser/develop/codecept-v3/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/thisuser/develop/codecept-v3/node_modules/codeceptjs/bin/codecept.js:228:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codecept-v3@1.0.0 test:def: `TS_NODE_PROJECT='./src/tests/tsconfig.json' codeceptjs def --config ./codecept.conf.js --output ./src/tests/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codecept-v3@1.0.0 test:def script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thisuser/.npm/_logs/2020-05-13T18_16_38_917Z-debug.log
thisuser@mymachine codecept-v3 %
```

> Helper file: extend_puppeteer_2_helper.ts

```js
"use strict"

class Extend_puppeteer_2 extends Helper {

  async nav_to_sign_up_page() {
    const page = this.helpers['Puppeteer'].page; // <-- This is where the error is: Property 'helpers' does not exist on type 'Extend_puppeteer_2'.ts(2339)

    const navigationPromise = page.waitForNavigation();

    await page.waitForSelector('.Header-old > .container-xl > .HeaderMenu > .d-lg-flex > .HeaderMenu-link:nth-child(3)');
    await page.click('.Header-old > .container-xl > .HeaderMenu > .d-lg-flex > .HeaderMenu-link:nth-child(3)');

    await navigationPromise;
  }

}

export = Extend_puppeteer_2;
```

### Details

* CodeceptJS version: 3.0.0-beta.2
* NodeJS Version: 12.16.3
* Operating System: macOS Catalina version 10.15.4
* puppeteer
* Configuration files below:

> codecept.conf.js
```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './src/tests/*_test.ts',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      show: true,
      windowSize: '1200x900'
    },
    Extend_puppeteer_2: {
      require: './extend_puppeteer_2_helper.ts',
    },
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codecept-v3',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  },
  require: ["ts-node/register"]
}
```

> ./src/tests/tsconfig.json (this is not the project-level tsconfig.json, but the one that is used when codeceptjs commands are run; project-level is pasted below)
```json
{
    "compilerOptions": {
      "target": "es2017",
      "moduleResolution": "node",
      "module": "commonjs",
      "sourceMap": true,
      "allowJs": true,
      "noEmit": true,
      "lib": ["es2016", "es2017", "dom"],
      "baseUrl": ".",
      "types": [
        "node",
        "./steps"
      ]
    }
}
```
> tsconfig.json (this is the project-level tsconfig.json file; the other one that is used when running codeceptjs commands is pasted above)
```json
{
    "compilerOptions": {
      "target": "es5",
      "moduleResolution": "node",
      "module": "commonjs",
      "sourceMap": true,
      "allowJs": true,
      "noEmit": true,
      "lib": ["es2016", "es2017", "dom"],
      "baseUrl": ".",
      "paths": {
        "*": ["*", "src/*"]
      }
    },
    "include": ["src/**/*"]
  }
```

> package.json
```json
{
  "name": "codecept-v3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "TS_NODE_PROJECT='./src/tests/tsconfig.json' ./node_modules/.bin/codeceptjs run --steps",
    "test:windows": "(set TS_NODE_PROJECT=./src/tests/tsconfig.json) && codeceptjs run --steps",
    "test:def": "TS_NODE_PROJECT='./src/tests/tsconfig.json' codeceptjs def --config ./codecept.conf.js --output ./src/tests/",
    "test:def:windows": "(set TS_NODE_PROJECT=./src/tests/tsconfig.json) && codeceptjs def  --config ./codecept.conf.js --output ./src/tests/"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "codeceptjs": "^3.0.0-beta.2",
    "puppeteer": "^3.0.4",
    "ts-node": "^8.10.1",
    "typescript": "^3.9.2"
  }
}
```

**Comment by PeterNgTr** [comment]
Shouldn’t we have this line before the class block?

const Helper = codeceptjs.helper;

**Comment by xray100** [comment]
Thanks for the input - I tried putting that in, didn't work.

I also tried leaving in the original line that was created, when used CodeceptJS's command to generate helper file, `const { Helper } = codeceptjs;`. This didn't work either.

I  had found instructions for using Typescript in CodeceptJS to be a little confusing on the official website. In order to set it up successfully to work with CodeceptJS v2, I used the instructions on the website as well as referred to [sample project](https://github.com/elukoyanov/codecept-typescript-example) using TS.

The helper example in the sample project was defined like [this](https://github.com/elukoyanov/codecept-typescript-example/blob/master/src/specs/e2e/helpers/randomGenerator.helper.ts), so I followed the same structure.

Digging around, I did find the following difference between CodeceptJS v2 and V3, which I think is causing this issue - the `helpers` property is missing in v3's type definition file:

![image](https://user-images.githubusercontent.com/19921221/81942966-d18e8e80-95c8-11ea-811f-e922ce5a3453.png)

**Comment by DavertMik** [comment]
@Vorobeyko could you take a look? 
Looks like a simple catch but I am not sure where did the typing went wrong

**Comment by jancorvus** [comment]
@xray100 does adding this to `tsconfig.json` help?
```json
{
  "ts-node": {
      "files": true
    },
  ...
}
```

**Comment by Vorobeyko** [comment]
Yes! And you need to update CodeceptJS version to version `3.0-beta.4`
