### ISSUE TITLE
Firefox profile can't be loaded in codeceptjs webdriver

### ISSUE THREAD

**Issue by maxim-savkin-abz** [codecept-js/CodeceptJS#2476]
#### What are you trying to achieve?
I'm trying to install extension in Firefox using profile created with firefox-profile-service in wdio plugin

#### What do you get instead?
I've got an error from Webdriver

```bash
Error: Failed to create session.
  Expected to read a START_MAP but instead have: START_COLLECTION. Last 128 characters read: EwZDBiZjgtZjViNS1jOGI0LWE4YjItMmI5ODc5ZTA4YzVkfS54cGlQSwUGAAAAAAMAAwDRAAAAsYUdAAAA"}}],"firstMatch":[{}]},"desiredCapabilities":

  Driver info: driver.version: unknown
      at startWebDriverSession (node_modules/webdriver/build/utils.js:45:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
I can load profile with only Webdriverio used and it works fine, profile with specified configurations and installed extension was launched properly, but the it doesn't work when I'm launching tests with Codeceptjs. Also I tried to launch test without desiredCapabilities property in codeceptjs config, in this case Firefox launches, but profile isn't applied

### Details

* CodeceptJS version: 2.6.6
* NodeJS Version: 10.16.0
* Operating System: macOS 10.14.4
* webdriverio
* Configuration file:

```js
// codecept.conf.js
exports.config = {
    tests: './tests/*_test.js',
    output: 'test-results',
    helpers: {
        WebDriver: {
            url: 'https://myapp.com',
            browser: 'firefox',
            host: '127.0.0.1',
            port: 4444,
            logLevel: 'silent',
            restart: true,
            keepBrowserState: false,
            keepCookies: false,
            windowSize: '1280x800',
            desiredCapabilities: [{
                browserName: 'firefox',
            }],
        },
    },
    plugins: {
        wdio: {
            enabled: true,
            services: [
                'selenium-standalone',
                'firefox-profile'
            ],
            firefoxProfile: {
                extensions: ['./myExtension.xpi'],
                'xpinstall.signatures.required': false,
                legacy: false,
            },
        },
    },
};
```

* Working config for wdio
```js
// wdio.conf.js
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'firefox',
    }],
    logLevel: 'silent',
    bail: 0,
    baseUrl: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone', 'firefox-profile'],
    firefoxProfile: {
        extensions: [
            './myExtension.xpi',
        ],
        'xpinstall.signatures.required': false,
    },
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
};
```

**Comment by xescuder** [comment]
I had a similar problem and I was not able to install extension from configuration file (but yes for Chrome). I've created a helper like this that works:

```
const event = require('codeceptjs').event;
const recorder = require('codeceptjs').recorder;
const container = require('codeceptjs').container;
const FirefoxProfile = require('firefox-profile');
const { promisify } = require('util');

module.exports = (config: any) => {
    const webDriver = container.helpers('WebDriver');

    event.dispatcher.on(event.all.before, function () {
        recorder.startUnlessRunning(); // start recording promises

        recorder.add(async () => {
            let browser = webDriver.options.browser;

            if (browser == 'firefox') {
                const options = {
                    destinationDirectory: './config/browsers/firefox',
                    'xpinstall.signatures.required': false,
                };

                const service = new FirefoxProfile(options);
                const encodedProfile = await promisify(service.encoded.bind(service))();

                webDriver.options.capabilities =
                {
                    'moz:firefoxOptions': {
                        profile: encodedProfile
                    }
                }
            }
        });
    });
}
```


And add your xpi file into ./config/browsers/firefox/extensions (it's expected the final folder extensions).

**Comment by maxim-savkin-abz** [comment]
@xescuder I've enabled your plugin in my configuration file. I see in console output that profile is created and specified in desiredCapabilities property,  but profile settings haven't been applied in browser anyway

**Comment by xescuder** [comment]
Have you specified destinationDirectory without subfolder '/extensions', and placed the extension in 'extensions' subfolder? A new browser window is shown with plugin installed, so I need to close this window from test.

**Comment by maxim-savkin-abz** [comment]
Thank you for answer. The issue was in extension file name, I'm trying to install signed extension and its name should include extension id, like {585280b0-ee78-428a-92c5-3fb3c0b85460}.xpi

**Comment by xescuder** [comment]
You're welcome. Great it's working.
