### ISSUE TITLE
resemble-helper tries to access comparison images for write purposes

### ISSUE THREAD

**Issue by shanplourde** [codecept-js/CodeceptJS#2480]
I'm trying to have Codecept's resemble-helper compare a read-only baseline file to a writable current file.

The resemble-helper fails when attempting to open the read-only baseline file with a 'file is read-only' error

Console output of error occurring:

```bash
    I screenshot element ".fld-prop-lbl-length>i", "be-field-property-lbl-icon"
Error: C:\perforce-MDM.Next\MDM.Next\splourde_mdmui-config-app-main\mdmui-config-app-ui\e2e\output\resemble-screenshots\base/be-field-property-error-icon.png is read-only
Error: C:\perforce-MDM.Next\MDM.Next\splourde_mdmui-config-app-main\mdmui-config-app-ui\e2e\output\resemble-screenshots\base/be-field-property-error-icon.png is read-only
    at fs.access (C:\perforce-MDM.Next\MDM.Next\splourde_mdmui-config-app-main\mdmui-config-app-ui\e2e\node_modules\codeceptjs-resemblehelper\index.js:47:15)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Uncaught undefined exception
```

It looks like the issue lies in codeceptjs-resemblehelper/index.js, lines 44 - 57:

```js
    // check whether the base and the screenshot images are present.
    fs.access(baseImage, fs.constants.F_OK | fs.constants.W_OK, (err) => {
      if (err) {
        throw new Error(
          `${baseImage} ${err.code === 'ENOENT' ? 'base image does not exist' : 'is read-only'}`);
      }
    });

    fs.access(actualImage, fs.constants.F_OK | fs.constants.W_OK, (err) => {
      if (err) {
        throw new Error(
          `${actualImage} ${err.code === 'ENOENT' ? 'screenshot image does not exist' : 'is read-only'}`);
      }
    });
```

I think that we just need to update this check to be F_OK | R_OK (write is not necessary for either file, I have confirmed this in a test run)

### Details

* CodeceptJS version: 2.6.1
* codeceptjs-resemblehelper version: 1.9.1
* Operating System: windows

**Comment by shanplourde** [comment]
Closing, will move to codeceptjs-resemblehelper GIT repo.
